[package]
name = "drain_filter_polyfill"
version = "0.1.3"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/whentze/drain_filter_polyfill.git"
description = "current nightly implementation of Vec::drain_filter, copypasted out for use on stable"

[dependencies]

